language: node_js
node_js:
- 12.16.1
deploy:
  provider: heroku
  api_key:
    secure: U4cQck10ipnbUAv2iZNMf9zMgsb6gymi5pIpjMPoAb4u3p9jnI2lznBy0vZ5LLg6hvOIOBVvD8oaKH7VbV3av8krxCUULtFjocdurP2enFcbtX/CbYLxQYVih3hP1jRmsF8RdNQN2vdAO3IAc1/CoG4UtiW8QilGvwu/IxL/GUs0eJbInEGWCgXNniEdSQqJbEERWGD5OltUKAGTsVzPMO6V7lYAJGCQnv10TBHWkC93R9K7mmuApdfyEt/pUhyHizdxmVQmxjh4L3dEtqYLr7RnriG3qy/e2llRB7N6y11IJrywZg0uvqWIRSn+ZE+0x492xQLdoMX8ohoyoqIXZl01AnjomywC4r8915ZzLKTCFjept0Oj9t8srFBH3o7M0nWqaOXohmEuM33zt8VKWq1o0hlHxEVPZ8d/rT4ljwncgAvDAwC17gUOrY4yRIvLqOCwxg3LBNOsGVR337ANALIHTjc7zZlJPDOXD3lu7jsVxfmzhQcBhHkBeSe3YwZTGG025eZeE4uB2C0TQ1i/GB/NIljk48ZJO8EfQ+R3fRS0aR8xmkYUZUSg2g6kD7Zclx4Q6pREWL6puLdem7OcjEupGrZrL3vHsq4v2Qf307nqW649DBGLrpc8ZfdL1YPlg4sy9H4hyw+W5MQ9S+tJV2VMhybdsBPgbNRBeyhfHug=
  app: samyanweather
  on:
    repo: yzenith/weather
