language: node_js
node_js:
- 12.x
deploy:
  provider: heroku
  api_key:
    secure: HgUOWx/LUCGc639dhVH/2nDC9+mVx1RhfskRLuTcr65c1K/I1QssHU+IlkupszwsRGSTaobHqCKHF1xgqTGAZtAu0phw4O+PqiKKBPXDjh1YENPpX4NWgqooSjwDctsGtaU/00dKp3W7lDo26AOeaB28J61HrbtFRnkmRcmkr/av8t0FT4zwRJDeRjB8G96N6lTjBf7sSC3DkAF41yRhRzxxUJoCcU9VqbgxY1102OPErUDah3V2tCegCYp2pMg84/cnQDFblOF6JcaKDxoEhiFzY2Zxb/SlP7+ZC8aD66fxBAxsm+bhU7hwyY/R/cCEa4dexfSZ1ORCxbI5atThnBGw9pIya5onv5gWVxr2XGPhj0e8NfQkPkF98kCTzXQcJCYjGrxc2goJUVSQiawyeqZLQNVWTeQTY1iK8YJ8FFnSincssf5GoFtC4/antELoCVWQLoLFFqM79AGXjnPT63mORolsQVIiN5CRGHHrZMRiuBf1nPmH4CIolOyLF5Mg8Pds+MzK1D6kEF8X6dEv+uwceSQWEuuUJKhj9ov3GWB1ViIZ+xbLy0sZ52BR/A85bnMSSbKbvCIOKfuSZlwh1IZR/NcYOSVKdUPy3CvchrSbjd8AaUpnCNZiqnQ9cqZn42KvVcuAc9f3JfEkrYYjr5BeIZhtVDB2eqepJlnNv/4=
  app: samyanweather
  on:
    repo: yzenith/weather
